spring:
  application:
    name: config-server
cloud:
  config:
    server:
      git:
        url:https://github.com/UtkuKaganYavuzdogannn/CursorLesson

        default-label: master
        search-paths:
        - configurations/
        - configurations/{application}
server:
  port: 8787